// ============================================================================
// Notification Event Catalog — single source of truth for push notifications.
//
// Transcribed from VAYUZ_AwesomLiving_NotificationMatrix_v2.xlsx (Phase-1
// scope). Every row of the matrix has an entry here, whether or not the
// backend can fire it yet — `implemented: false` rows are documented gaps,
// not silent omissions. See `implementation_note` on those rows for what's
// still missing (usually a whole detection engine: live fall trigger,
// GLK bed-state debounce, Hub/System health heartbeats, camera health).
//
// Used by service/notification_service.js to decide, for an event that DOES
// fire: whether it's a push / feed-only / digest item, whether it ignores
// quiet hours, and which app screen it should deep-link to.
// ============================================================================

const TIER = { BASE: 'Base', PRO: 'Pro', ALL: 'All' };

const PRIORITY = { P0: 'P0', P1: 'P1', P2: 'P2', P3: 'P3' };

const DELIVERY = { PUSH: 'push', FEED: 'feed', DIGEST: 'digest' };

// Recipient roles as named in the matrix. Today the backend only has one
// app-user account per resident (the `creator`, who stands in for
// "primary_caregiver"). `emergency_contact`, `family`, `care_manager`, and
// `admin` are not yet real app logins with their own push tokens — see
// docs/push-notifications-integration.md for the gap and follow-up.
const RECIPIENT = {
  PRIMARY_CAREGIVER: 'primary_caregiver',
  EMERGENCY_CONTACT: 'emergency_contact',
  FAMILY: 'family',
  CARE_MANAGER: 'care_manager',
  ADMIN: 'admin',
};

/**
 * @typedef {Object} NotificationEventDef
 * @property {number} id                 Row # in the matrix
 * @property {string} module             Matrix "Module" column
 * @property {string} device             Matrix "Device" column (matrix's own label)
 * @property {string} event              Matrix "Event" column
 * @property {string} backend_event      Matrix "Backend Event" column — stable key
 * @property {string} tier               Base | Pro | All
 * @property {string} priority           P0 | P1 | P2 | P3
 * @property {string} priority_label     e.g. "Emergency", "Warning"
 * @property {string} delivery           push | feed | digest
 * @property {boolean} quiet_hours_exempt  true = always sends, even in quiet hours
 * @property {string[]} recipients       RECIPIENT roles from the matrix
 * @property {string} trigger            Matrix "Trigger Condition" column
 * @property {string} debounce           Matrix "Debounce / Confirmation Rule" column
 * @property {string} escalation         Matrix "Escalation Rule" column
 * @property {string} screen             App screen this push should deep-link to
 * @property {boolean} implemented       Does the backend actually fire this today?
 * @property {string} [implementation_note] What's wired, or what's missing
 */

/** @type {NotificationEventDef[]} */
const notification_events_list = [
  {
    id: 1,
    module: 'Fall Detection',
    device: 'AltumView (camera)',
    event: 'Fall Detected',
    backend_event: 'ALTUM_FALL_DETECTED',
    tier: TIER.PRO,
    priority: PRIORITY.P0,
    priority_label: 'Emergency',
    delivery: DELIVERY.PUSH,
    quiet_hours_exempt: true,
    recipients: [RECIPIENT.PRIMARY_CAREGIVER, RECIPIENT.EMERGENCY_CONTACT, RECIPIENT.CARE_MANAGER],
    trigger: 'AltumView fall algorithm; corroborate with GLK bed-exit / inactivity where available',
    debounce: 'Confirm on device algo; do not fire on single ambiguous frame',
    escalation:
      'Primary now; Emergency + Care Mgr after 1 min; repeat 2 min; auto-dial responder/ambulance if unacknowledged after 5 min',
    screen: 'BathroomSafetyScreen',
    implemented: true,
    implementation_note:
      'Wired via the AltumView "Alert Forwarding" webhook (server/service/altum_alert_forwarding_service.js, POST /webhooks/altum/alert-forwarding) -- fires on action_type "Fallen". Requires the one-time AltumView portal setup (RSA keypair + AES key) described at the top of that file before it goes live in production.',
  },
  {
    id: 2,
    module: 'Fall Detection',
    device: 'GLK + Motion/Presence',
    event: 'Prolonged Inactivity — possible fall',
    backend_event: 'INACTIVITY_POSSIBLE_FALL',
    tier: TIER.BASE,
    priority: PRIORITY.P1,
    priority_label: 'Critical',
    delivery: DELIVERY.PUSH,
    quiet_hours_exempt: true,
    recipients: [RECIPIENT.PRIMARY_CAREGIVER, RECIPIENT.CARE_MANAGER],
    trigger:
      'No movement in an active area, OR bed-exit with no return, sustained beyond learned baseline (camera-free)',
    debounce:
      'Camera-free. Requires sustained inactivity vs 2-wk baseline; gentle in-home speaker check before alerting family',
    escalation:
      'Primary + Care Mgr after failed in-home check; repeat 3 min; responder tier if unacknowledged',
    screen: 'RoomSensorScreen',
    implemented: true,
    implementation_note:
      'Wired to the existing room_state no-motion checker (start_room_alert_checker) at its final "emergency" escalation tier only -- the earlier "warning" tier stays feed/socket-only, per the matrix\'s own goal of cutting v1 over-notification. This is a fixed no-motion timeout, NOT the 2-week learned-baseline + in-home-speaker-check flow the matrix describes -- that\'s a real gap, flagged here rather than silently claimed.',
  },
  {
    id: 3,
    module: 'Fall Detection',
    device: 'AltumView',
    event: 'Fall Resolved',
    backend_event: 'ALTUM_FALL_RESOLVED',
    tier: TIER.PRO,
    priority: PRIORITY.P3,
    priority_label: 'Information',
    delivery: DELIVERY.FEED,
    quiet_hours_exempt: false,
    recipients: [RECIPIENT.PRIMARY_CAREGIVER, RECIPIENT.FAMILY],
    trigger: 'Fall state cleared',
    debounce: '—',
    escalation: 'None',
    screen: 'BathroomSafetyScreen',
    implemented: false,
    implementation_note: 'Depends on #1 (live fall trigger) existing first.',
  },
  // ── Rows 3.1 / 3.2: NOT transcribed from the client's notification
  // matrix (v3 only covers Fall Detected / Fall Resolved for AltumView).
  // Added because the Sentinare sensor also raises Help Requested (hand
  // wave), Fire, Fighting, Restricted Zone, Overstay and Absence events,
  // and service/altum_alert_service.js now ingests every event type the
  // device can emit -- dropping them silently would mean a real fire or
  // help-wave alert reaching the backend and going nowhere. Re-map or
  // remove these if the client's matrix later assigns them explicit rows.
  {
    id: 3.1,
    module: 'Fall Detection',
    device: 'AltumView (camera)',
    event: 'Help Requested (hand wave)',
    backend_event: 'ALTUM_HELP_REQUESTED',
    tier: TIER.PRO,
    priority: PRIORITY.P0,
    priority_label: 'Emergency',
    delivery: DELIVERY.PUSH,
    quiet_hours_exempt: true,
    recipients: [RECIPIENT.PRIMARY_CAREGIVER, RECIPIENT.EMERGENCY_CONTACT],
    trigger: 'AltumView HandWave event (event_type 5) -- resident waved at the camera for help',
    debounce: 'On-device gesture algorithm; no additional backend debounce',
    escalation: 'Same tier as the physical emergency button',
    screen: 'BathroomSafetyScreen',
    implemented: true,
    implementation_note:
      'Wired in service/altum_alert_service.js. Reaches the backend via the alert poller (no setup) and/or the Alert Forwarding webhook (portal setup), deduped by Altum alert id.',
  },
  {
    id: 3.2,
    module: 'Fall Detection',
    device: 'AltumView (camera)',
    event: 'Other camera alert (Fire / Fighting / Restricted Zone / Overstay / Absence)',
    backend_event: 'ALTUM_SENSOR_ALERT',
    tier: TIER.PRO,
    priority: PRIORITY.P1,
    priority_label: 'Critical',
    delivery: DELIVERY.PUSH,
    // Deliberately NOT exempt at the row level: this row covers both a fire
    // (must wake you) and an Overstay/Absence (must not, at 3am). The caller
    // in altum_alert_service.js passes bypass_quiet_hours per event instead.
    quiet_hours_exempt: false,
    recipients: [RECIPIENT.PRIMARY_CAREGIVER, RECIPIENT.CARE_MANAGER],
    trigger:
      'Any non-fall AltumView event type (2, 3, 4, 10, 11), or an event type we do not yet recognise',
    debounce: 'On-device algorithm',
    escalation: 'Primary caregiver immediately',
    screen: 'BathroomSafetyScreen',
    implemented: true,
    implementation_note:
      'Catch-all row. altum_alert_service.js passes an explicit title/body built from the specific event type, so the push reads as "Fire Detected" etc rather than this row generic copy -- the row supplies priority, quiet-hours policy, mute category and deep link only.',
  },
  {
    id: 4,
    module: 'Health & Sleep',
    device: 'GLK Vital Tracker',
    event: 'Sleep Started',
    backend_event: 'GLK_SLEEP_STARTED',
    tier: TIER.ALL,
    priority: PRIORITY.P3,
    priority_label: 'Information',
    delivery: DELIVERY.PUSH,
    quiet_hours_exempt: false,
    recipients: [RECIPIENT.PRIMARY_CAREGIVER],
    trigger: 'Debounced sleep-onset from glk_bedstate',
    debounce: 'From glk_bedstate state, not raw packet',
    escalation: 'None',
    screen: 'SleepDetailScreen',
    implemented: true,
    implementation_note:
      'Wired to glk_bedstate_service.js start_glk_bedstate_checker(). Sleep onset detected after SLEEP_ONSET_MIN (5 min) of sustained in_bed + low movement. Debounced via in-memory bed-state machine — not raw in_bed flag.',
  },
  {
    id: 5,
    module: 'Health & Sleep',
    device: 'GLK Vital Tracker',
    event: 'Sleep Ended',
    backend_event: 'GLK_SLEEP_ENDED',
    tier: TIER.ALL,
    priority: PRIORITY.P3,
    priority_label: 'Information',
    delivery: DELIVERY.PUSH,
    quiet_hours_exempt: false,
    recipients: [RECIPIENT.PRIMARY_CAREGIVER],
    trigger: 'Debounced sleep-end from glk_bedstate',
    debounce: 'From glk_bedstate state',
    escalation: 'None',
    screen: 'SleepDetailScreen',
    implemented: true,
    implementation_note:
      'Wired to glk_bedstate_service.js. Sleep end fires when resident is out of bed for >= SLEEP_ONSET_MIN (5 min) during an active sleep session — distinguishes bathroom trips from actual wake-up.',
  },
  {
    id: 6,
    module: 'Health & Sleep',
    device: 'GLK Vital Tracker',
    event: 'Restless / Interrupted Sleep',
    backend_event: 'GLK_SLEEP_INTERRUPTED',
    tier: TIER.ALL,
    priority: PRIORITY.P3,
    priority_label: 'Information',
    delivery: DELIVERY.DIGEST,
    quiet_hours_exempt: false,
    recipients: [RECIPIENT.PRIMARY_CAREGIVER],
    trigger: 'glk_bedstate restless_period (clustered movement), not per-blip',
    debounce: 'One event per restless cluster (RESTLESS_MIN_HITS in window); NOT per toss',
    escalation: 'None',
    screen: 'SleepDetailScreen',
    implemented: true,
    implementation_note:
      'Wired to glk_bedstate_service.js. Fires when >= RESTLESS_MIN_HITS (5) movement events occur within a RESTLESS_WINDOW_S (300s) sliding window during active sleep. 30-min cooldown between alerts. Digest delivery — creates alert_log for daily narrative, no push.',
  },
  {
    id: 7,
    module: 'Health & Sleep',
    device: 'GLK Vital Tracker',
    event: 'Poor Sleep (vs their norm)',
    backend_event: 'GLK_POOR_SLEEP_SCORE',
    tier: TIER.ALL,
    priority: PRIORITY.P3,
    priority_label: 'Information',
    delivery: DELIVERY.DIGEST,
    quiet_hours_exempt: false,
    recipients: [RECIPIENT.PRIMARY_CAREGIVER, RECIPIENT.FAMILY],
    trigger: "Sleep score below the resident's personal baseline",
    debounce: 'Trend vs baseline over the night',
    escalation: 'None',
    screen: 'SleepDetailScreen',
    implemented: false,
    implementation_note:
      'Needs personal-baseline computation (2-wk learned norm) + daily digest. The glk_bedstate engine now tracks sleep sessions but scoring requires historical analysis — flagged for Sprint 3 AI features.',
  },
  {
    id: 8,
    module: 'Health & Sleep',
    device: 'GLK Vital Tracker',
    event: 'Good Sleep Completed',
    backend_event: 'GLK_GOOD_SLEEP_COMPLETED',
    tier: TIER.ALL,
    priority: PRIORITY.P3,
    priority_label: 'Information',
    delivery: DELIVERY.DIGEST,
    quiet_hours_exempt: false,
    recipients: [RECIPIENT.PRIMARY_CAREGIVER, RECIPIENT.FAMILY],
    trigger: 'Full night, no concerns',
    debounce: '—',
    escalation: 'None',
    screen: 'SleepDetailScreen',
    implemented: false,
    implementation_note:
      'Same baseline gap as #7 — needs sleep quality scoring against personal norm.',
  },
  {
    id: 9,
    module: 'Health & Sleep',
    device: 'GLK Vital Tracker',
    event: 'Elevated Heart Rate',
    backend_event: 'GLK_ELEVATED_HEART_RATE',
    tier: TIER.ALL,
    priority: PRIORITY.P2,
    priority_label: 'Warning (P1 if extreme & sustained)',
    delivery: DELIVERY.PUSH,
    quiet_hours_exempt: false, // becomes true when severity is 'critical' -- see notification_service.js
    recipients: [RECIPIENT.PRIMARY_CAREGIVER, RECIPIENT.CARE_MANAGER],
    trigger:
      'HR sustained above (personal baseline + margin) for ≥ N min, movement/null samples excluded',
    debounce:
      '≥ N consecutive valid min; exclude movement & null; compare to personal resting baseline',
    escalation: 'Escalate to Emergency Contact only if sustained/extreme',
    screen: 'VitalsDetailScreen',
    implemented: true,
    implementation_note:
      'Wired to start_emfit_alert_checker. Guards: (1) in_bed must be true on current reading, (2) 5-min settling cooldown after bed entry, (3) HR/RR must both be non-zero. Two severity thresholds (danger → P2/warning, critical → P1/bypasses quiet hours). Static thresholds only — personal baseline not yet implemented.',
  },
  {
    id: 10,
    module: 'Health & Sleep',
    device: 'GLK Vital Tracker',
    event: 'Low Heart Rate',
    backend_event: 'GLK_LOW_HEART_RATE',
    tier: TIER.ALL,
    priority: PRIORITY.P2,
    priority_label: 'Warning (P1 if extreme)',
    delivery: DELIVERY.PUSH,
    quiet_hours_exempt: false,
    recipients: [RECIPIENT.PRIMARY_CAREGIVER, RECIPIENT.CARE_MANAGER],
    trigger: 'HR sustained below baseline threshold; EXCLUDE normal deep-sleep bradycardia',
    debounce: 'deep-sleep low HR is normal — require baseline-relative drop',
    escalation: 'Escalate only if sustained/extreme',
    screen: 'VitalsDetailScreen',
    implemented: true,
    implementation_note:
      'Same guards as #9: in_bed gate + 5-min settling cooldown + non-zero HR/RR. Static thresholds only — personal baseline not yet implemented.',
  },
  {
    id: 11,
    module: 'Health & Sleep',
    device: 'GLK Vital Tracker',
    event: 'High Respiratory Rate',
    backend_event: 'GLK_HIGH_RESPIRATORY_RATE',
    tier: TIER.ALL,
    priority: PRIORITY.P2,
    priority_label: 'Warning (P1 if extreme)',
    delivery: DELIVERY.PUSH,
    quiet_hours_exempt: false,
    recipients: [RECIPIENT.PRIMARY_CAREGIVER],
    trigger: 'RR sustained above baseline for ≥ N min, movement excluded',
    debounce: 'Sustained + baseline + movement-exclude',
    escalation: 'Escalate if sustained',
    screen: 'VitalsDetailScreen',
    implemented: true,
    implementation_note:
      'Same guards as #9: in_bed gate + 5-min settling cooldown + non-zero HR/RR.',
  },
  {
    id: 12,
    module: 'Health & Sleep',
    device: 'GLK Vital Tracker',
    event: 'Low Respiratory Rate',
    backend_event: 'GLK_LOW_RESPIRATORY_RATE',
    tier: TIER.ALL,
    priority: PRIORITY.P2,
    priority_label: 'Warning (P1 if extreme)',
    delivery: DELIVERY.PUSH,
    quiet_hours_exempt: false,
    recipients: [RECIPIENT.PRIMARY_CAREGIVER],
    trigger: 'RR sustained below baseline for ≥ N min, movement excluded',
    debounce: 'Sustained + baseline + movement-exclude',
    escalation: 'Escalate if sustained',
    screen: 'VitalsDetailScreen',
    implemented: true,
    implementation_note:
      'Same guards as #9: in_bed gate + 5-min settling cooldown + non-zero HR/RR.',
  },
  {
    id: 13,
    module: 'Health & Sleep',
    device: 'GLK Vital Tracker',
    event: 'Resident Left Bed',
    backend_event: 'GLK_RESIDENT_LEFT_BED',
    tier: TIER.ALL,
    priority: PRIORITY.P3,
    priority_label: 'Information',
    delivery: DELIVERY.FEED,
    quiet_hours_exempt: false,
    recipients: [RECIPIENT.PRIMARY_CAREGIVER],
    trigger: 'DEBOUNCED bed_exit from glk_bedstate (sustained absence ≥30s) — NOT raw in_bed=false',
    debounce:
      'glk_bedstate EXIT_CONFIRM_S=30s. Raw in_bed flaps ~126×/night — must never trigger directly',
    escalation: 'None (normal nightly event)',
    screen: 'SleepDetailScreen',
    implemented: true,
    implementation_note:
      'Wired to glk_bedstate_service.js. Fires after EXIT_CONFIRM_S (30s) of sustained absence. Feed-only — creates alert_log + socket emit, no push.',
  },
  {
    id: 14,
    module: 'Health & Sleep',
    device: 'GLK Vital Tracker',
    event: 'Resident Returned to Bed',
    backend_event: 'GLK_RESIDENT_RETURNED_TO_BED',
    tier: TIER.ALL,
    priority: PRIORITY.P3,
    priority_label: 'Information',
    delivery: DELIVERY.FEED,
    quiet_hours_exempt: false,
    recipients: [RECIPIENT.PRIMARY_CAREGIVER],
    trigger: 'Debounced bed_return from glk_bedstate (sustained presence ≥10s)',
    debounce: 'glk_bedstate RETURN_CONFIRM_S=10s',
    escalation: 'None',
    screen: 'SleepDetailScreen',
    implemented: true,
    implementation_note:
      'Wired to glk_bedstate_service.js. Fires after RETURN_CONFIRM_S (10s) of sustained presence. Feed-only — creates alert_log + socket emit, no push.',
  },
  {
    id: 15,
    module: 'Health & Sleep',
    device: 'GLK Vital Tracker',
    event: 'Out of Bed Too Long',
    backend_event: 'GLK_OUT_OF_BED_TOO_LONG',
    tier: TIER.ALL,
    priority: PRIORITY.P2,
    priority_label: 'Warning',
    delivery: DELIVERY.PUSH,
    quiet_hours_exempt: true,
    recipients: [RECIPIENT.PRIMARY_CAREGIVER, RECIPIENT.CARE_MANAGER],
    trigger:
      'Debounced bed_exit with NO bed_return for > 15 min; ONLY during night sleep window (21:00-09:00 IST)',
    debounce: 'Built on debounced bed-state + intention_to_leave; not raw flag',
    escalation: 'Escalate to Care Mgr if unresolved',
    screen: 'SleepDetailScreen',
    implemented: true,
    implementation_note:
      'Wired to glk_bedstate_service.js. Only fires during night sleep window (9 PM – 9 AM IST). Threshold: 15 min. Repeats every OUT_OF_BED_REPEAT_MIN (10 min) while still out. Push delivery, quiet_hours_exempt.',
  },
  {
    id: 16,
    module: 'Emergency',
    device: 'Emergency Button',
    event: 'Emergency Button Pressed',
    backend_event: 'EMERGENCY_BUTTON_PRESSED',
    tier: TIER.ALL,
    priority: PRIORITY.P0,
    priority_label: 'Emergency',
    delivery: DELIVERY.PUSH,
    quiet_hours_exempt: true,
    recipients: [
      RECIPIENT.PRIMARY_CAREGIVER,
      RECIPIENT.EMERGENCY_CONTACT,
      RECIPIENT.FAMILY,
      RECIPIENT.CARE_MANAGER,
    ],
    trigger: 'Button pressed',
    debounce: 'None (immediate)',
    escalation:
      'All now; repeat 1 min; auto-dial responder/ambulance if unacknowledged after X min; offer TTLock door-unlock',
    screen: 'SafetyScreen',
    implemented: true,
    implementation_note:
      'Wired to handle_switch() in zigbee_service.js on the "single" press action. Repeat/auto-dial/door-unlock escalation is NOT built (no responder/ambulance integration exists) -- only the initial push fires.',
  },
  {
    id: 17,
    module: 'Emergency',
    device: 'Emergency Button',
    event: 'Emergency Cancelled',
    backend_event: 'EMERGENCY_BUTTON_CANCELLED',
    tier: TIER.ALL,
    priority: PRIORITY.P3,
    priority_label: 'Information',
    delivery: DELIVERY.FEED,
    quiet_hours_exempt: false,
    recipients: [RECIPIENT.PRIMARY_CAREGIVER, RECIPIENT.EMERGENCY_CONTACT, RECIPIENT.FAMILY],
    trigger: 'Button cancel',
    debounce: '—',
    escalation: 'None',
    screen: 'SafetyScreen',
    implemented: false,
    implementation_note:
      'The zigbee switch handler does not currently distinguish a "cancel" action from a press -- only "single" press is handled. No change needed either way since this row is feed-only, but there is no dedicated cancel event today.',
  },
  {
    id: 18,
    module: 'Environment',
    device: 'Window / Door Sensor',
    event: 'Door Opened',
    backend_event: 'DOOR_OPENED',
    tier: TIER.ALL,
    priority: PRIORITY.P3,
    priority_label: 'Information',
    delivery: DELIVERY.PUSH,
    quiet_hours_exempt: false,
    recipients: [RECIPIENT.PRIMARY_CAREGIVER],
    trigger: 'Door open',
    debounce: '—',
    escalation: 'None',
    screen: 'SensorsScreen',
    implemented: true,
    implementation_note:
      'Already feed-only in practice: the contact checker only ever pushes at "warning"/"emergency" (see #20). The instant "info" open state is written to alert_log/socket but never pushed -- no change was needed.',
  },
  {
    id: 19,
    module: 'Environment',
    device: 'Window / Door Sensor',
    event: 'Door Closed',
    backend_event: 'DOOR_CLOSED',
    tier: TIER.ALL,
    priority: PRIORITY.P3,
    priority_label: 'Information',
    delivery: DELIVERY.PUSH,
    quiet_hours_exempt: false,
    recipients: [RECIPIENT.PRIMARY_CAREGIVER],
    trigger: 'Door closed',
    debounce: '—',
    escalation: 'None',
    screen: 'SensorsScreen',
    implemented: true,
    implementation_note:
      'Closing resets alert_state (auto-resolves the open alert_log) but does not write a distinct "closed" feed entry today -- pre-existing gap, not a push concern since this row is feed-only anyway.',
  },
  {
    id: 20,
    module: 'Environment',
    device: 'Window / Door Sensor',
    event: 'Door Left Open',
    backend_event: 'DOOR_LEFT_OPEN',
    tier: TIER.ALL,
    priority: PRIORITY.P2,
    priority_label: 'Warning',
    delivery: DELIVERY.PUSH,
    quiet_hours_exempt: true,
    recipients: [RECIPIENT.PRIMARY_CAREGIVER],
    trigger: 'Door open > X min (night stricter)',
    debounce: 'Open continuously > threshold',
    escalation: 'Repeat every 15 min until closed',
    screen: 'SensorsScreen',
    implemented: true,
    implementation_note:
      'Wired to start_contact_alert_checker\'s "warning"/"emergency" tiers, classified as a door via device.room/sensor_type (see classify_contact_device() in health_logs.js). Repeat interval is whatever the checker already uses (5 min prod / shortened in testing_flag), not the matrix\'s 15 min -- existing checker logic was left untouched per scope, only push delivery was added.',
  },
  {
    id: 21,
    module: 'Environment',
    device: 'Window / Door Sensor',
    event: 'Window Opened',
    backend_event: 'WINDOW_OPENED',
    tier: TIER.ALL,
    priority: PRIORITY.P3,
    priority_label: 'Information',
    delivery: DELIVERY.PUSH,
    quiet_hours_exempt: false,
    recipients: [RECIPIENT.PRIMARY_CAREGIVER],
    trigger: 'Window open',
    debounce: '—',
    escalation: 'None',
    screen: 'SensorsScreen',
    implemented: true,
    implementation_note:
      'Push notification on window open (within monitoring window). Same wiring as #18, window-classified.',
  },
  {
    id: 22,
    module: 'Environment',
    device: 'Window / Door Sensor',
    event: 'Window Closed',
    backend_event: 'WINDOW_CLOSED',
    tier: TIER.ALL,
    priority: PRIORITY.P3,
    priority_label: 'Information',
    delivery: DELIVERY.PUSH,
    quiet_hours_exempt: false,
    recipients: [RECIPIENT.PRIMARY_CAREGIVER],
    trigger: 'Window closed',
    debounce: '—',
    escalation: 'None',
    screen: 'SensorsScreen',
    implemented: true,
    implementation_note:
      'Push notification on window close (within monitoring window). Same wiring as #19, window-classified.',
  },
  {
    id: 23,
    module: 'Environment',
    device: 'Window / Door Sensor',
    event: 'Window Left Open',
    backend_event: 'WINDOW_LEFT_OPEN',
    tier: TIER.ALL,
    priority: PRIORITY.P2,
    priority_label: 'Warning',
    delivery: DELIVERY.PUSH,
    quiet_hours_exempt: true,
    recipients: [RECIPIENT.PRIMARY_CAREGIVER],
    trigger: 'Window open > X min',
    debounce: 'Open continuously > threshold',
    escalation: 'Repeat every 15 min until closed',
    screen: 'SensorsScreen',
    implemented: true,
    implementation_note: 'Same wiring as #20, window-classified.',
  },
  {
    id: 24,
    module: 'Security',
    device: 'CP Plus CCTV',
    event: 'Camera Offline',
    backend_event: 'CAMERA_OFFLINE',
    tier: TIER.PRO,
    priority: PRIORITY.P2,
    priority_label: 'Warning',
    delivery: DELIVERY.PUSH,
    quiet_hours_exempt: false,
    recipients: [RECIPIENT.PRIMARY_CAREGIVER, RECIPIENT.ADMIN],
    trigger: 'No stream/heartbeat > X min',
    debounce: 'Offline > threshold (debounce transient drops)',
    escalation: 'Repeat 30 min until online',
    screen: 'CameraScreen',
    implemented: true,
    implementation_note:
      'Wired in health_logs.js start_camera_health_checker(). Pi camera-wrapper POSTs heartbeats to /api/camera/heartbeat every 30s, updating camera_last_seen on CpPlus device docs. Cron runs every 30s checking for cameras offline > 2 min. Fires CAMERA_OFFLINE push (P2) once per offline session, tracked via alert_state with key "camera_offline:<device_id>". Auto-clears when heartbeat resumes (fires CAMERA_ONLINE feed).',
  },
  {
    id: 25,
    module: 'Security',
    device: 'CP Plus CCTV',
    event: 'Camera Online',
    backend_event: 'CAMERA_ONLINE',
    tier: TIER.PRO,
    priority: PRIORITY.P3,
    priority_label: 'Information',
    delivery: DELIVERY.PUSH,
    quiet_hours_exempt: false,
    recipients: [RECIPIENT.ADMIN],
    trigger: 'Stream restored',
    debounce: '—',
    escalation: 'None',
    screen: 'CameraScreen',
    implemented: true,
    implementation_note:
      'Wired in health_logs.js start_camera_health_checker(). Fires CAMERA_ONLINE push when a previously-offline camera receives a heartbeat.',
  },
  {
    id: 26,
    module: 'Security',
    device: 'CP Plus CCTV',
    event: 'Camera Storage Full',
    backend_event: 'CAMERA_STORAGE_FULL',
    tier: TIER.PRO,
    priority: PRIORITY.P2,
    priority_label: 'Warning',
    delivery: DELIVERY.PUSH,
    quiet_hours_exempt: false,
    recipients: [RECIPIENT.ADMIN],
    trigger: 'Storage full',
    debounce: '—',
    escalation: 'Repeat 60 min until resolved',
    screen: 'CameraScreen',
    implemented: false,
    implementation_note: 'No camera storage monitoring exists. Not built in this pass.',
  },
  {
    id: 27,
    module: 'Security',
    device: 'CP Plus CCTV',
    event: 'Recording Stopped',
    backend_event: 'CAMERA_RECORDING_STOPPED',
    tier: TIER.PRO,
    priority: PRIORITY.P2,
    priority_label: 'Warning',
    delivery: DELIVERY.PUSH,
    quiet_hours_exempt: false,
    recipients: [RECIPIENT.PRIMARY_CAREGIVER, RECIPIENT.ADMIN],
    trigger: 'Recording stopped',
    debounce: 'Debounce transient',
    escalation: 'None',
    screen: 'CameraScreen',
    implemented: false,
    implementation_note: 'No recording-state monitoring exists. Not built in this pass.',
  },
  {
    id: 28,
    module: 'Security',
    device: 'CP Plus CCTV',
    event: 'Recording Started',
    backend_event: 'CAMERA_RECORDING_STARTED',
    tier: TIER.PRO,
    priority: PRIORITY.P3,
    priority_label: 'Information',
    delivery: DELIVERY.FEED,
    quiet_hours_exempt: false,
    recipients: [RECIPIENT.ADMIN],
    trigger: 'Recording started',
    debounce: '—',
    escalation: 'None',
    screen: 'CameraScreen',
    implemented: false,
    implementation_note: 'Depends on #27.',
  },
  {
    id: 29,
    module: 'Motion & Presence',
    device: 'Motion/Presence Detector',
    event: 'Presence Detected',
    backend_event: 'PRESENCE_DETECTED',
    tier: TIER.ALL,
    priority: PRIORITY.P3,
    priority_label: 'Information',
    delivery: DELIVERY.PUSH,
    quiet_hours_exempt: false,
    recipients: [RECIPIENT.PRIMARY_CAREGIVER],
    trigger: 'Presence in room',
    debounce:
      'Raw substrate for activity baseline & inactivity detection — never an individual push',
    escalation: 'None',
    screen: 'SensorsScreen',
    implemented: true,
    implementation_note:
      'Dispatched from handle_presence_sensor() in zigbee_service.js on occupancy=true. Feed-only — no push.',
  },
  {
    id: 30,
    module: 'Motion & Presence',
    device: 'Motion/Presence Detector',
    event: 'Presence Lost',
    backend_event: 'PRESENCE_LOST',
    tier: TIER.ALL,
    priority: PRIORITY.P3,
    priority_label: 'Information',
    delivery: DELIVERY.PUSH,
    quiet_hours_exempt: false,
    recipients: [RECIPIENT.PRIMARY_CAREGIVER],
    trigger: 'Presence lost',
    debounce: 'Feeds inactivity clock',
    escalation: 'None',
    screen: 'SensorsScreen',
    implemented: true,
    implementation_note:
      'Dispatched from handle_presence_sensor() in zigbee_service.js on occupancy=false. Feed-only — no push.',
  },
  {
    id: 31,
    module: 'Motion & Presence',
    device: 'Motion/Presence Detector',
    event: 'Motion Detected',
    backend_event: 'MOTION_DETECTED',
    tier: TIER.ALL,
    priority: PRIORITY.P3,
    priority_label: 'Information',
    delivery: DELIVERY.PUSH,
    quiet_hours_exempt: false,
    recipients: [RECIPIENT.PRIMARY_CAREGIVER],
    trigger: 'Motion',
    debounce: '—',
    escalation: 'None',
    screen: 'SensorsScreen',
    implemented: true,
    implementation_note:
      'Dispatched from handle_motion_sensor() in zigbee_service.js on occupancy=true. Feed-only — no push.',
  },
  {
    id: 32,
    module: 'Motion & Presence',
    device: 'Motion/Presence Detector',
    event: 'Motion Stopped',
    backend_event: 'MOTION_STOPPED',
    tier: TIER.ALL,
    priority: PRIORITY.P3,
    priority_label: 'Information',
    delivery: DELIVERY.PUSH,
    quiet_hours_exempt: false,
    recipients: [RECIPIENT.PRIMARY_CAREGIVER],
    trigger: 'Motion stopped',
    debounce: 'Feeds inactivity clock',
    escalation: 'None',
    screen: 'SensorsScreen',
    implemented: true,
    implementation_note:
      'Dispatched from handle_motion_sensor() in zigbee_service.js on occupancy=false. Feed-only — no push.',
  },
  {
    id: 33,
    module: 'Motion & Presence',
    device: 'Motion/Presence Detector',
    event: 'Room Occupied',
    backend_event: 'ROOM_OCCUPIED',
    tier: TIER.ALL,
    priority: PRIORITY.P3,
    priority_label: 'Information',
    delivery: DELIVERY.PUSH,
    quiet_hours_exempt: false,
    recipients: [RECIPIENT.PRIMARY_CAREGIVER],
    trigger: 'Room occupied',
    debounce: '—',
    escalation: 'None',
    screen: 'SensorsScreen',
    implemented: true,
    implementation_note:
      'Dispatched from both motion and presence handlers when room_state transitions to occupied/activity_detected. Feed-only — no push.',
  },
  {
    id: 34,
    module: 'Motion & Presence',
    device: 'Motion/Presence Detector',
    event: 'Room Vacant',
    backend_event: 'ROOM_VACANT',
    tier: TIER.ALL,
    priority: PRIORITY.P3,
    priority_label: 'Information',
    delivery: DELIVERY.PUSH,
    quiet_hours_exempt: false,
    recipients: [RECIPIENT.PRIMARY_CAREGIVER],
    trigger: 'Room vacant',
    debounce: '—',
    escalation: 'None',
    screen: 'SensorsScreen',
    implemented: true,
    implementation_note:
      'Dispatched from both motion and presence handlers when room_state transitions to empty. Feed-only — no push.',
  },
  {
    id: 35,
    module: 'System Health',
    device: 'Hub (Raspberry Pi)',
    event: 'Hub Offline / Not Reporting',
    backend_event: 'HUB_OFFLINE',
    tier: TIER.ALL,
    priority: PRIORITY.P1,
    priority_label: 'Critical',
    delivery: DELIVERY.PUSH,
    quiet_hours_exempt: true,
    recipients: [RECIPIENT.PRIMARY_CAREGIVER, RECIPIENT.ADMIN],
    trigger: 'No heartbeat from hub > X min',
    debounce: 'No heartbeat > threshold (a silent dead system is the worst failure)',
    escalation: 'Repeat until hub back or acknowledged',
    screen: 'HomeStatusScreen',
    implemented: true,
    implementation_note:
      'Wired in hub_service.js start_hub_health_checker(). Phase 1 (quick offline) fires HUB_OFFLINE push when no heartbeat arrives for > 30s (2 missed pings). Phase 1b repeats every 15 min while hub stays offline. hub_offline_notified_at on hub_status model tracks the repeat interval; cleared on next heartbeat (hub back online).',
  },
  {
    id: 36,
    module: 'System Health',
    device: 'Hub UPS',
    event: 'Running on Battery (Mains Lost)',
    backend_event: 'MAINS_LOST',
    tier: TIER.ALL,
    priority: PRIORITY.P2,
    priority_label: 'Warning',
    delivery: DELIVERY.PUSH,
    quiet_hours_exempt: true,
    recipients: [RECIPIENT.PRIMARY_CAREGIVER, RECIPIENT.ADMIN],
    trigger: 'Mains lost, on UPS',
    debounce: 'From resilience watchdog',
    escalation: 'Escalate if battery critical',
    screen: 'HomeStatusScreen',
    implemented: true,
    implementation_note:
      'Wired in hub_service.js record_heartbeat(). The Pi heartbeat now accepts an optional mains_status field ("mains" | "battery"). On the mains→battery transition, a MAINS_LOST push is dispatched once. Hub controller and hub_status model updated to accept and store the field. Pi-side resilience watchdog must report mains_status in the heartbeat payload.',
  },
  {
    id: 37,
    module: 'System Health',
    device: 'Hub UPS',
    event: 'Hub Battery Low',
    backend_event: 'HUB_BATTERY_LOW',
    tier: TIER.ALL,
    priority: PRIORITY.P2,
    priority_label: 'Warning',
    delivery: DELIVERY.PUSH,
    quiet_hours_exempt: true,
    recipients: [RECIPIENT.PRIMARY_CAREGIVER, RECIPIENT.ADMIN],
    trigger: 'UPS battery below threshold',
    debounce: 'From resilience watchdog',
    escalation: 'Escalate to safe-shutdown warning',
    screen: 'HomeStatusScreen',
    implemented: false,
    implementation_note: 'Same gap as #36.',
  },
  {
    id: 38,
    module: 'System Health',
    device: 'Router',
    event: 'Internet Failover to Cellular',
    backend_event: 'WAN_FAILOVER',
    tier: TIER.ALL,
    priority: PRIORITY.P3,
    priority_label: 'Information',
    delivery: DELIVERY.FEED,
    quiet_hours_exempt: false,
    recipients: [RECIPIENT.ADMIN],
    trigger: 'Primary WAN down, on 4G',
    debounce: 'From resilience watchdog',
    escalation: 'None',
    screen: 'HomeStatusScreen',
    implemented: false,
    implementation_note: 'Same watchdog gap as #36.',
  },
  {
    id: 39,
    module: 'System Health',
    device: 'Any sensor',
    event: 'Device / Sensor Offline',
    backend_event: 'DEVICE_OFFLINE',
    tier: TIER.ALL,
    priority: PRIORITY.P2,
    priority_label: 'Warning',
    delivery: DELIVERY.PUSH,
    quiet_hours_exempt: false,
    recipients: [RECIPIENT.PRIMARY_CAREGIVER, RECIPIENT.ADMIN],
    trigger: 'A paired device stops reporting > X min',
    debounce: 'Per-device heartbeat timeout',
    escalation: 'Repeat until back',
    screen: 'SensorsScreen',
    implemented: true,
    implementation_note:
      'Wired in health_logs.js start_device_offline_checker(). Cron runs every 5 minutes, checks all active Zigbee devices for last zigbee_log older than 1 hour (is_device_active threshold). Fires DEVICE_OFFLINE push and repeats every 30 minutes while offline, tracked via alert_state with key "offline:<device_id>". Auto-clears when a new log arrives. Started in socket/server.js alongside other checkers.',
  },
  {
    id: 40,
    module: 'System Health',
    device: 'Hub (Raspberry Pi)',
    event: 'Hub Back Online',
    backend_event: 'HUB_ONLINE',
    tier: TIER.ALL,
    priority: PRIORITY.P3,
    priority_label: 'Information',
    delivery: DELIVERY.PUSH,
    quiet_hours_exempt: false,
    recipients: [RECIPIENT.PRIMARY_CAREGIVER, RECIPIENT.ADMIN],
    trigger: 'First heartbeat after hub was offline',
    debounce: 'Single notification on offline→online transition',
    escalation: 'None',
    screen: 'HomeStatusScreen',
    implemented: true,
    implementation_note:
      'Wired in hub_service.js record_heartbeat(). Fires once when came_online is true (hub was offline, first heartbeat arrives). No repeat — single informational push.',
  },

  // ── Room Occupancy Detection (3-device: threshold motion + room motion + door/window) ──
  {
    id: 41,
    module: 'Motion & Presence',
    device: 'Room Occupancy Group (2× Motion + Door/Window)',
    event: 'Long Stay Alert',
    backend_event: 'OCCUPANCY_LONG_STAY',
    tier: TIER.ALL,
    priority: PRIORITY.P2,
    priority_label: 'Warning',
    delivery: DELIVERY.PUSH,
    quiet_hours_exempt: false,
    recipients: [RECIPIENT.PRIMARY_CAREGIVER],
    trigger:
      'Room continuously occupied longer than the configured long-stay thresholds (3 escalating levels: L1 default 30 min, L2 default 60 min, L3 default 120 min)',
    debounce:
      '3 escalating levels per occupancy session; level_reached tracks highest fired (0-3). Resets to 0 on vacant→occupied transition only.',
    escalation:
      'L1 warning → L2 critical → L3 emergency. Each level fires its own alert_log entry and push with per-level title/body/severity override via dispatch_notification. Independent from no-motion alert #42.',
    screen: 'RoomSensorScreen',
    implemented: true,
    implementation_note:
      'Wired in health_logs.js start_occupancy_alert_checker(). Cron runs every 30 seconds, checks all room_occupancy_state docs where state=occupied. Compares occupied_since against long_stay_level_1/2/3_min from room_occupancy_settings (with night mode variants). Fires L1→L2→L3 sequentially as thresholds are crossed; long_stay_level_reached (0-3) prevents re-firing. Per-level title, body, and severity passed to dispatch_notification as overrides. Resets only on vacant transition (ALL_ALERTS_RESET constant).',
  },
  {
    id: 42,
    module: 'Motion & Presence',
    device: 'Room Occupancy Group (2× Motion + Door/Window)',
    event: 'Room Occupancy — Motion Not Detected',
    backend_event: 'OCCUPANCY_NO_MOTION',
    tier: TIER.ALL,
    priority: PRIORITY.P1,
    priority_label: 'Critical',
    delivery: DELIVERY.PUSH,
    quiet_hours_exempt: true,
    recipients: [RECIPIENT.PRIMARY_CAREGIVER, RECIPIENT.CARE_MANAGER],
    trigger:
      'No room motion detected for longer than the configured no-motion thresholds (3 escalating levels: L1 default 15 min, L2 default 30 min, L3 default 60 min) while room is occupied',
    debounce:
      '3 escalating levels per no-motion episode; level_reached tracks highest fired (0-3). Resets to 0 when room motion resumes (can re-fire if motion stops again within same occupancy session).',
    escalation:
      'L1 warning → L2 critical → L3 emergency. Each level fires its own alert_log entry and push with per-level title/body/severity override via dispatch_notification.',
    screen: 'RoomSensorScreen',
    implemented: true,
    implementation_note:
      'Wired in health_logs.js start_occupancy_alert_checker(). Checks last_room_motion_at against no_motion_level_1/2/3_min from room_occupancy_settings (with night mode variants). Fires L1→L2→L3 sequentially; no_motion_level_reached (0-3) prevents re-firing. Per-level title, body, and severity passed to dispatch_notification as overrides. Resets on room motion (NO_MOTION_RESET constant in room_occupancy_service.js handle_room_motion), so levels can re-fire if motion stops again within the same occupancy session.',
  },
  {
    id: 43,
    module: 'Motion & Presence',
    device: 'Room Occupancy Group (2× Motion + Door/Window)',
    event: 'Occupancy Unconfirmed (Stuck Occupied)',
    backend_event: 'OCCUPANCY_UNCONFIRMED',
    tier: TIER.ALL,
    priority: PRIORITY.P2,
    priority_label: 'Warning',
    delivery: DELIVERY.PUSH,
    quiet_hours_exempt: false,
    recipients: [RECIPIENT.PRIMARY_CAREGIVER],
    trigger:
      'Room stuck in occupied state with zero corroborating signal (no motion, no door activity) for longer than the safety ceiling (default 4 hours). Genuinely ambiguous — could mean something is wrong, or the exit was simply never detected.',
    debounce: 'Single alert per stuck-occupied episode (no escalation levels)',
    escalation:
      'None — single level only. Different from long-stay and no-motion alerts which have 3 escalating levels.',
    screen: 'RoomSensorScreen',
    implemented: true,
    implementation_note:
      'Wired in health_logs.js start_occupancy_alert_checker(). Checks both last_room_motion_at and last_door_cycle_at/last_threshold_motion_at against safety_ceiling_hours. Fires once (safety_ceiling_alert_sent flag). No escalation levels — single alert only. Resets on vacant transition (SAFETY_CEILING_RESET constant). Distinct message framing from the standard no-motion alert per spec Section 8.',
  },

  // ── Room Occupancy V4 (2-sensor: doorway PIR + inside PIR, no door contact) ──
  {
    id: 44,
    module: 'Motion & Presence',
    device: 'Room Occupancy V4 (2× PIR, no door contact)',
    event: 'V4 Inactivity Alert — no movement in bathroom',
    backend_event: 'V4_INACTIVITY_ALERT',
    tier: TIER.ALL,
    priority: PRIORITY.P0,
    priority_label: 'Emergency',
    delivery: DELIVERY.PUSH,
    quiet_hours_exempt: true,
    recipients: [RECIPIENT.PRIMARY_CAREGIVER, RECIPIENT.FAMILY],
    trigger:
      'No inside-sensor motion for silence threshold (15 min day / 10 min night), chime window expired, alert escalated to family.',
    debounce: 'Chime check window (2 attempts × 90s) before family push. Repeats every 5 min.',
    escalation: 'Repeats every 5 min until acknowledged or movement resumes.',
    screen: 'RoomSensorScreen',
    implemented: true,
    implementation_note:
      'Wired in occupancy_v4_service.js via the pure state machine tick(). Silence thresholds: day 900s, night 600s. Chime window: 2 attempts × 90s. Alert repeat: 300s. All timing is inside the state machine — this service only dispatches.',
  },
  {
    id: 45,
    module: 'Motion & Presence',
    device: 'Room Occupancy V4 (2× PIR, no door contact)',
    event: 'V4 Alert Repeat',
    backend_event: 'V4_ALERT_REPEAT',
    tier: TIER.ALL,
    priority: PRIORITY.P0,
    priority_label: 'Emergency',
    delivery: DELIVERY.PUSH,
    quiet_hours_exempt: true,
    recipients: [RECIPIENT.PRIMARY_CAREGIVER, RECIPIENT.FAMILY],
    trigger: 'Repeating inactivity alert — still no movement after initial alert.',
    debounce: 'Every 5 min until acknowledged or movement.',
    escalation: 'None beyond repeat.',
    screen: 'RoomSensorScreen',
    implemented: true,
    implementation_note:
      'Emitted by occupancyStateMachine tick() every alertRepeatS (300s production, 30s test). Dispatched by occupancy_v4_service.js.',
  },
  {
    id: 46,
    module: 'Motion & Presence',
    device: 'Room Occupancy V4 (2× PIR, no door contact)',
    event: 'V4 All Clear — movement resumed',
    backend_event: 'V4_ALL_CLEAR',
    tier: TIER.ALL,
    priority: PRIORITY.P3,
    priority_label: 'Information',
    delivery: DELIVERY.PUSH,
    quiet_hours_exempt: false,
    recipients: [RECIPIENT.PRIMARY_CAREGIVER, RECIPIENT.FAMILY],
    trigger: 'Movement detected after an inactivity alert was active.',
    debounce: 'Automatic, within seconds of motion resuming.',
    escalation: 'None.',
    screen: 'RoomSensorScreen',
    implemented: true,
    implementation_note:
      'Emitted by occupancyStateMachine on doorway or inside motion while in ALERTED state. Fixed wording per spec 5.3.',
  },
  {
    id: 47,
    module: 'Motion & Presence',
    device: 'Room Occupancy V4 (2× PIR, no door contact)',
    event: 'V4 Long Stay',
    backend_event: 'V4_LONG_STAY',
    tier: TIER.ALL,
    priority: PRIORITY.P2,
    priority_label: 'Warning',
    delivery: DELIVERY.PUSH,
    quiet_hours_exempt: false,
    recipients: [RECIPIENT.PRIMARY_CAREGIVER],
    trigger:
      'Room occupied continuously for 45 / 60 / 90 min (3 escalating levels).',
    debounce: 'One push per level per occupancy session. Resets on vacant.',
    escalation: 'L1 warning → L2 critical → L3 emergency (full-screen, requires ack).',
    screen: 'RoomSensorScreen',
    implemented: true,
    implementation_note:
      'Emitted by occupancyStateMachine tick(). longStayS: [2700, 3600, 5400]. L3 has requiresAck + critical. Dispatched by occupancy_v4_service.js.',
  },
  {
    id: 48,
    module: 'Motion & Presence',
    device: 'Room Occupancy V4 (2× PIR, no door contact)',
    event: 'V4 Safety Ceiling — stuck in bathroom 4+ hours',
    backend_event: 'V4_SAFETY_CEILING',
    tier: TIER.ALL,
    priority: PRIORITY.P0,
    priority_label: 'Emergency',
    delivery: DELIVERY.PUSH,
    quiet_hours_exempt: true,
    recipients: [RECIPIENT.PRIMARY_CAREGIVER, RECIPIENT.FAMILY],
    trigger: 'Room continuously occupied for 4 hours (safetyCeilingS: 14400).',
    debounce: 'Single alert per occupancy session.',
    escalation: 'None — single push. Requires acknowledgement.',
    screen: 'RoomSensorScreen',
    implemented: true,
    implementation_note:
      'Emitted by occupancyStateMachine tick(). safetyCeilingS: 14400. requiresAck + critical. Dispatched by occupancy_v4_service.js.',
  },
];

const get_event = (backend_event) =>
  notification_events_list.find((e) => e.backend_event === backend_event);

const implemented_events_list = notification_events_list.filter((e) => e.implemented);

// List of the matrix's own section headings (e.g. "Fall Detection", "Health
// & Sleep"), derived from the catalog's `module` column. NOT used by the
// app's mute toggles -- see `get_device_categories()` below for that. Kept
// for reference/reporting since `module` still labels every catalog row.
const get_modules = () => [...new Set(notification_events_list.map((e) => e.module))];

// ----------------------------------------------------------------------------
// Device-wise mute categories -- what the app's "turn off alerts for this
// device" switches actually correspond to. This is deliberately a DIFFERENT
// grouping from `module` above: `module` follows the matrix's section
// headings (e.g. INACTIVITY_POSSIBLE_FALL is filed under "Fall Detection"
// even though it's driven by motion/presence sensor data, not the Eltum
// camera), while `device_category` groups by the physical device the user
// actually sees a switch for in the app: GLK/Emfit vital tracker, the
// motion+presence sensors, the emergency button, window/door contact
// sensors, and the Eltum (AltumView) camera.
//
// Events with no entry here (camera health/CP Plus, hub/system health) have
// no device-level toggle -- they're only affected by the master
// notifications_enabled switch (users.js). That's intentional: those aren't
// among the 5 device switches the app exposes today.
const DeviceCategory = {
  GLK_EMFIT: 'GLK/Emfit',
  MOTION_PRESENCE: 'Motion & Presence',
  BUTTON: 'Emergency Button',
  WINDOW_DOOR: 'Window/Door Sensor',
  ELTUM: 'Eltum',
};

const backend_event_device_category = {
  // Eltum (AltumView camera)
  ALTUM_FALL_DETECTED: DeviceCategory.ELTUM,
  ALTUM_FALL_RESOLVED: DeviceCategory.ELTUM,
  ALTUM_HELP_REQUESTED: DeviceCategory.ELTUM,
  ALTUM_SENSOR_ALERT: DeviceCategory.ELTUM,

  // Motion & Presence -- includes INACTIVITY_POSSIBLE_FALL, since that's
  // driven by motion/presence sensor data, not the camera (per explicit
  // product decision -- differs from its catalog `module` of "Fall Detection").
  INACTIVITY_POSSIBLE_FALL: DeviceCategory.MOTION_PRESENCE,
  PRESENCE_DETECTED: DeviceCategory.MOTION_PRESENCE,
  PRESENCE_LOST: DeviceCategory.MOTION_PRESENCE,
  MOTION_DETECTED: DeviceCategory.MOTION_PRESENCE,
  MOTION_STOPPED: DeviceCategory.MOTION_PRESENCE,
  ROOM_OCCUPIED: DeviceCategory.MOTION_PRESENCE,
  ROOM_VACANT: DeviceCategory.MOTION_PRESENCE,

  // GLK/Emfit vital tracker
  GLK_SLEEP_STARTED: DeviceCategory.GLK_EMFIT,
  GLK_SLEEP_ENDED: DeviceCategory.GLK_EMFIT,
  GLK_SLEEP_INTERRUPTED: DeviceCategory.GLK_EMFIT,
  GLK_POOR_SLEEP_SCORE: DeviceCategory.GLK_EMFIT,
  GLK_GOOD_SLEEP_COMPLETED: DeviceCategory.GLK_EMFIT,
  GLK_ELEVATED_HEART_RATE: DeviceCategory.GLK_EMFIT,
  GLK_LOW_HEART_RATE: DeviceCategory.GLK_EMFIT,
  GLK_HIGH_RESPIRATORY_RATE: DeviceCategory.GLK_EMFIT,
  GLK_LOW_RESPIRATORY_RATE: DeviceCategory.GLK_EMFIT,
  GLK_RESIDENT_LEFT_BED: DeviceCategory.GLK_EMFIT,
  GLK_RESIDENT_RETURNED_TO_BED: DeviceCategory.GLK_EMFIT,
  GLK_OUT_OF_BED_TOO_LONG: DeviceCategory.GLK_EMFIT,

  // Emergency button
  EMERGENCY_BUTTON_PRESSED: DeviceCategory.BUTTON,
  EMERGENCY_BUTTON_CANCELLED: DeviceCategory.BUTTON,

  // Window/door contact sensor
  DOOR_OPENED: DeviceCategory.WINDOW_DOOR,
  DOOR_CLOSED: DeviceCategory.WINDOW_DOOR,
  DOOR_LEFT_OPEN: DeviceCategory.WINDOW_DOOR,
  WINDOW_OPENED: DeviceCategory.WINDOW_DOOR,
  WINDOW_CLOSED: DeviceCategory.WINDOW_DOOR,
  WINDOW_LEFT_OPEN: DeviceCategory.WINDOW_DOOR,

  // Room occupancy (3-device group) — grouped under Motion & Presence since
  // the underlying hardware is motion + contact sensors.
  OCCUPANCY_LONG_STAY: DeviceCategory.MOTION_PRESENCE,
  OCCUPANCY_NO_MOTION: DeviceCategory.MOTION_PRESENCE,
  OCCUPANCY_UNCONFIRMED: DeviceCategory.MOTION_PRESENCE,

  // Room occupancy V4 (2-sensor: doorway PIR + inside PIR)
  V4_INACTIVITY_ALERT: DeviceCategory.MOTION_PRESENCE,
  V4_ALERT_REPEAT: DeviceCategory.MOTION_PRESENCE,
  V4_ALL_CLEAR: DeviceCategory.MOTION_PRESENCE,
  V4_LONG_STAY: DeviceCategory.MOTION_PRESENCE,
  V4_SAFETY_CEILING: DeviceCategory.MOTION_PRESENCE,
};

notification_events_list.forEach((e) => {
  e.device_category = backend_event_device_category[e.backend_event] || null;
});

// Authoritative list of the app's 5 device-wise mute switches. Derived from
// DeviceCategory (not hand-duplicated) so it can't drift out of sync.
const get_device_categories = () => Object.values(DeviceCategory);

// ----------------------------------------------------------------------------
// Standardized push/UX copy -- transcribed from
// VAYUZ_AwesomLiving_NotificationMatrix_FINAL_v3.xlsx (the "v1 push/UX fields
// restored" merge). `notification_title` is a fixed string per event.
// `notification_message` and `deep_link` are templates with {placeholder}
// tokens filled in at send time by notification_service.js's
// render_template() -- see that file for the exact variable names each event
// needs (e.g. {resident}, {location}, {cameraName}, {deviceName},
// {residentId}, {deviceId}, {hubId}).
//
// `user_action` / `notification_category` / `dismissible` are UI hints for
// the app, passed through in the push `data` payload as-is.
// `repeat_notification` / `expiry` are DOCUMENTATION of the intended
// cadence/lifetime from the matrix -- the backend does not yet implement a
// generic repeat-until-acknowledged scheduler for every row (the door/window
// and vital checkers have their own independent repeat logic; events with a
// "no repeat" in production are unaffected). Not silently claimed as built;
// see notification_service.js for exactly what's wired.
const backend_event_copy = {
  ALTUM_HELP_REQUESTED: {
    notification_title: 'Help Requested',
    notification_message: '{resident} waved for help on camera. Tap to verify and respond.',
    user_action: 'Call Resident · View Live Camera · Unlock Door',
    deep_link: '/live-camera/{deviceId}',
    notification_category: 'Safety',
    dismissible: false,
    repeat_notification: 'Every 2 min until acknowledged',
    expiry: 'Until acknowledged',
  },
  // Fallback copy only -- altum_alert_service.js passes an explicit
  // title/body naming the actual event (Fire Detected, Restricted Zone
  // Entry, ...). These strings show only if a caller omits both.
  ALTUM_SENSOR_ALERT: {
    notification_title: 'Camera Alert',
    notification_message: 'The camera reported an event for {resident}. Tap to view.',
    user_action: 'View Live Camera · Call Resident',
    deep_link: '/live-camera/{deviceId}',
    notification_category: 'Safety',
    dismissible: false,
    repeat_notification: 'No',
    expiry: 'Until acknowledged',
  },
  ALTUM_FALL_DETECTED: {
    notification_title: 'Fall Detected',
    notification_message: 'A possible fall was detected for {resident}. Tap to verify and respond.',
    user_action: 'Call Resident · View Live Camera · Unlock Door',
    deep_link: '/live-camera/{deviceId}',
    notification_category: 'Safety',
    dismissible: false,
    repeat_notification: 'Every 2 min until acknowledged',
    expiry: 'Until acknowledged',
  },
  INACTIVITY_POSSIBLE_FALL: {
    notification_title: 'Possible Fall / No Movement Detected',
    notification_message:
      "{resident} hasn't moved in room longer than usual. We checked in — please verify.",
    user_action: 'Call Resident · View Timeline',
    deep_link: '/timeline/{residentId}',
    notification_category: 'Safety',
    dismissible: false,
    repeat_notification: 'Every 3 min until acknowledged',
    expiry: 'Until acknowledged',
  },
  ALTUM_FALL_RESOLVED: {
    notification_title: 'Fall Resolved',
    notification_message: 'The fall alert for {resident} has been resolved.',
    user_action: 'View Timeline',
    deep_link: '/timeline/{residentId}',
    notification_category: 'Safety',
    dismissible: true,
    repeat_notification: 'No',
    expiry: '24 hours',
  },
  GLK_SLEEP_STARTED: {
    notification_title: 'Sleep Started',
    notification_message: '{resident} has fallen asleep.',
    user_action: 'View Device',
    deep_link: '/device/{deviceId}',
    notification_category: 'Sleep',
    dismissible: true,
    repeat_notification: 'No',
    expiry: '8 hours',
  },
  GLK_SLEEP_ENDED: {
    notification_title: 'Sleep Ended',
    notification_message: '{resident} is now awake.',
    user_action: 'View Device',
    deep_link: '/device/{deviceId}',
    notification_category: 'Sleep',
    dismissible: true,
    repeat_notification: 'No',
    expiry: '8 hours',
  },
  GLK_SLEEP_INTERRUPTED: {
    notification_title: 'Sleep Interrupted (in Daily Narrative)',
    notification_message: "{resident}'s sleep was interrupted during the night.",
    user_action: 'View Sleep Report',
    deep_link: '/sleep-report/{residentId}',
    notification_category: 'Sleep',
    dismissible: true,
    repeat_notification: 'No',
    expiry: 'Rolls into next daily digest',
  },
  GLK_POOR_SLEEP_SCORE: {
    notification_title: 'Poor Sleep (in Daily Narrative)',
    notification_message: '{resident} had poorer sleep than their usual pattern last night.',
    user_action: 'View Sleep Report',
    deep_link: '/sleep-report/{residentId}',
    notification_category: 'Sleep',
    dismissible: true,
    repeat_notification: 'No',
    expiry: 'Rolls into next daily digest',
  },
  GLK_GOOD_SLEEP_COMPLETED: {
    notification_title: 'Good Sleep (in Daily Narrative)',
    notification_message: '{resident} slept well last night.',
    user_action: 'View Sleep Report',
    deep_link: '/sleep-report/{residentId}',
    notification_category: 'Sleep',
    dismissible: true,
    repeat_notification: 'No',
    expiry: 'Rolls into next daily digest',
  },
  GLK_ELEVATED_HEART_RATE: {
    notification_title: 'High Heart Rate',
    notification_message:
      "{resident}'s heart rate has been elevated above their normal range. Please check on them.",
    user_action: 'Call Resident',
    deep_link: '/vitals/{residentId}',
    notification_category: 'Health',
    dismissible: false,
    repeat_notification: 'Every 5 min until acknowledged',
    expiry: 'Until acknowledged',
  },
  GLK_LOW_HEART_RATE: {
    notification_title: 'Low Heart Rate',
    notification_message:
      "{resident}'s heart rate has dropped below their normal range. Please check on them.",
    user_action: 'Call Resident',
    deep_link: '/vitals/{residentId}',
    notification_category: 'Health',
    dismissible: false,
    repeat_notification: 'Every 5 min until acknowledged',
    expiry: 'Until acknowledged',
  },
  GLK_HIGH_RESPIRATORY_RATE: {
    notification_title: 'High Breathing Rate',
    notification_message:
      "{resident}'s breathing rate is higher than normal. Please check on them.",
    user_action: 'Call Resident',
    deep_link: '/vitals/{residentId}',
    notification_category: 'Health',
    dismissible: false,
    repeat_notification: 'Every 5 min until acknowledged',
    expiry: 'Until acknowledged',
  },
  GLK_LOW_RESPIRATORY_RATE: {
    notification_title: 'Low Breathing Rate',
    notification_message: "{resident}'s breathing rate is lower than normal. Please check on them.",
    user_action: 'Call Resident',
    deep_link: '/vitals/{residentId}',
    notification_category: 'Health',
    dismissible: false,
    repeat_notification: 'Every 5 min until acknowledged',
    expiry: 'Until acknowledged',
  },
  GLK_RESIDENT_LEFT_BED: {
    notification_title: 'Left Bed',
    notification_message: '{resident} has left the bed.',
    user_action: 'View Device',
    deep_link: '/device/{deviceId}',
    notification_category: 'Motion',
    dismissible: true,
    repeat_notification: 'No',
    expiry: '4 hours',
  },
  GLK_RESIDENT_RETURNED_TO_BED: {
    notification_title: 'Returned to Bed',
    notification_message: '{resident} has returned to bed.',
    user_action: 'View Device',
    deep_link: '/device/{deviceId}',
    notification_category: 'Motion',
    dismissible: true,
    repeat_notification: 'No',
    expiry: '4 hours',
  },
  GLK_OUT_OF_BED_TOO_LONG: {
    notification_title: 'Out of Bed Too Long',
    notification_message: '{resident} has been out of bed longer than usual. Please check on them.',
    user_action: 'View Timeline · View Live Camera (Pro only)',
    deep_link: '/timeline/{residentId}',
    notification_category: 'Safety',
    dismissible: true,
    repeat_notification: 'Every 10 min until resolved',
    expiry: 'Until resolved',
  },
  EMERGENCY_BUTTON_PRESSED: {
    notification_title: 'Emergency Alert',
    notification_message: '{resident} pressed the emergency button. Respond now.',
    user_action: 'Call Resident · Unlock Door',
    deep_link: '/emergency/{residentId}',
    notification_category: 'Emergency',
    dismissible: false,
    repeat_notification: 'Every 1 min until acknowledged',
    expiry: 'Until acknowledged',
  },
  EMERGENCY_BUTTON_CANCELLED: {
    notification_title: 'Emergency Cancelled',
    notification_message: 'The emergency alert for {resident} has been cancelled.',
    user_action: 'View Timeline',
    deep_link: '/timeline/{residentId}',
    notification_category: 'Emergency',
    dismissible: true,
    repeat_notification: 'No',
    expiry: '24 hours',
  },
  DOOR_OPENED: {
    notification_title: 'Door Opened',
    notification_message: 'The door has been opened.',
    user_action: 'View Device',
    deep_link: '/device/{deviceId}',
    notification_category: 'Security',
    dismissible: true,
    repeat_notification: 'No',
    expiry: '2 hours',
  },
  DOOR_CLOSED: {
    notification_title: 'Door Closed',
    notification_message: 'The door has been closed.',
    user_action: 'View Device',
    deep_link: '/device/{deviceId}',
    notification_category: 'Security',
    dismissible: true,
    repeat_notification: 'No',
    expiry: '2 hours',
  },
  DOOR_LEFT_OPEN: {
    notification_title: 'Door Left Open',
    notification_message: 'The door has been open for a while.',
    user_action: 'View Device',
    deep_link: '/device/{deviceId}',
    notification_category: 'Security',
    dismissible: true,
    repeat_notification: 'Every 15 min until closed',
    expiry: 'Until resolved',
  },
  WINDOW_OPENED: {
    notification_title: 'Window Opened',
    notification_message: 'The window has been opened.',
    user_action: 'View Device',
    deep_link: '/device/{deviceId}',
    notification_category: 'Environment',
    dismissible: true,
    repeat_notification: 'No',
    expiry: '2 hours',
  },
  WINDOW_CLOSED: {
    notification_title: 'Window Closed',
    notification_message: 'The window has been closed.',
    user_action: 'View Device',
    deep_link: '/device/{deviceId}',
    notification_category: 'Environment',
    dismissible: true,
    repeat_notification: 'No',
    expiry: '2 hours',
  },
  WINDOW_LEFT_OPEN: {
    notification_title: 'Window Left Open',
    notification_message: 'The window has been open for a while.',
    user_action: 'View Device',
    deep_link: '/device/{deviceId}',
    notification_category: 'Environment',
    dismissible: true,
    repeat_notification: 'Every 15 min until closed',
    expiry: 'Until resolved',
  },
  CAMERA_OFFLINE: {
    notification_title: 'Camera Offline',
    notification_message: '{cameraName} is offline. Please check the connection.',
    user_action: 'View Device',
    deep_link: '/device/{deviceId}',
    notification_category: 'Camera',
    dismissible: true,
    repeat_notification: 'Every 30 min until online',
    expiry: 'Until resolved',
  },
  CAMERA_ONLINE: {
    notification_title: 'Camera Online',
    notification_message: '{cameraName} is back online.',
    user_action: 'View Device',
    deep_link: '/device/{deviceId}',
    notification_category: 'Camera',
    dismissible: true,
    repeat_notification: 'No',
    expiry: '6 hours',
  },
  CAMERA_STORAGE_FULL: {
    notification_title: 'Storage Full',
    notification_message: '{cameraName} storage is full. Recording may stop.',
    user_action: 'View Device',
    deep_link: '/device/{deviceId}',
    notification_category: 'Camera',
    dismissible: true,
    repeat_notification: 'Every 60 min until resolved',
    expiry: 'Until resolved',
  },
  CAMERA_RECORDING_STOPPED: {
    notification_title: 'Recording Stopped',
    notification_message: 'Recording on {cameraName} has stopped.',
    user_action: 'View Device',
    deep_link: '/device/{deviceId}',
    notification_category: 'Camera',
    dismissible: true,
    repeat_notification: 'No',
    expiry: '6 hours',
  },
  CAMERA_RECORDING_STARTED: {
    notification_title: 'Recording Started',
    notification_message: 'Recording on {cameraName} has started.',
    user_action: 'View Device',
    deep_link: '/device/{deviceId}',
    notification_category: 'Camera',
    dismissible: true,
    repeat_notification: 'No',
    expiry: '6 hours',
  },
  PRESENCE_DETECTED: {
    notification_title: 'Presence Detected',
    notification_message: 'Presence detected in room.',
    user_action: 'View Device',
    deep_link: '/device/{deviceId}',
    notification_category: 'Motion',
    dismissible: true,
    repeat_notification: 'No',
    expiry: '2 hours',
  },
  PRESENCE_LOST: {
    notification_title: 'Presence Lost',
    notification_message: 'No presence detected in room.',
    user_action: 'View Device',
    deep_link: '/device/{deviceId}',
    notification_category: 'Motion',
    dismissible: true,
    repeat_notification: 'No',
    expiry: '2 hours',
  },
  MOTION_DETECTED: {
    notification_title: 'Motion Detected',
    notification_message: 'Motion detected in room.',
    user_action: 'View Device',
    deep_link: '/device/{deviceId}',
    notification_category: 'Motion',
    dismissible: true,
    repeat_notification: 'No',
    expiry: '2 hours',
  },
  MOTION_STOPPED: {
    notification_title: 'Motion Stopped',
    notification_message: 'Motion has stopped in room.',
    user_action: 'View Device',
    deep_link: '/device/{deviceId}',
    notification_category: 'Motion',
    dismissible: true,
    repeat_notification: 'No',
    expiry: '2 hours',
  },
  ROOM_OCCUPIED: {
    notification_title: 'Room Occupied',
    notification_message: 'Room is now occupied.',
    user_action: 'View Device',
    deep_link: '/device/{deviceId}',
    notification_category: 'Motion',
    dismissible: true,
    repeat_notification: 'No',
    expiry: '2 hours',
  },
  ROOM_VACANT: {
    notification_title: 'Room Vacant',
    notification_message: 'Room is now vacant.',
    user_action: 'View Device',
    deep_link: '/device/{deviceId}',
    notification_category: 'Motion',
    dismissible: true,
    repeat_notification: 'No',
    expiry: '2 hours',
  },
  HUB_OFFLINE: {
    notification_title: 'Monitoring Hub Offline',
    notification_message:
      "The monitoring hub at {resident}'s home has stopped reporting. Live monitoring may be paused.",
    user_action: 'View System Status',
    deep_link: '/system-health/{hubId}',
    notification_category: 'System Health',
    dismissible: false,
    repeat_notification: 'Every 15 min until hub is back online or acknowledged',
    expiry: 'Until resolved',
  },
  HUB_ONLINE: {
    notification_title: 'Monitoring Hub Online',
    notification_message:
      "The monitoring hub at {resident}'s home is back online. Live monitoring has resumed.",
    user_action: 'View System Status',
    deep_link: '/system-health/{hubId}',
    notification_category: 'System Health',
    dismissible: true,
    repeat_notification: 'No',
    expiry: '2 hours',
  },
  MAINS_LOST: {
    notification_title: 'Running on Backup Battery',
    notification_message:
      "Power at {resident}'s home was lost. The hub is running on backup battery.",
    user_action: 'View System Status',
    deep_link: '/system-health/{hubId}',
    notification_category: 'System Health',
    dismissible: true,
    repeat_notification: 'No',
    expiry: 'Until mains power restored',
  },
  HUB_BATTERY_LOW: {
    notification_title: 'Hub Battery Low',
    notification_message:
      "The backup battery for {resident}'s monitoring hub is running low. Monitoring may stop soon.",
    user_action: 'View System Status',
    deep_link: '/system-health/{hubId}',
    notification_category: 'System Health',
    dismissible: false,
    repeat_notification: 'Every 15 min until resolved',
    expiry: 'Until resolved',
  },
  WAN_FAILOVER: {
    notification_title: 'Switched to Backup Internet',
    notification_message:
      'The home internet connection was lost; the hub switched to cellular backup.',
    user_action: 'View System Status',
    deep_link: '/system-health/{hubId}',
    notification_category: 'System Health',
    dismissible: true,
    repeat_notification: 'No',
    expiry: '6 hours',
  },
  DEVICE_OFFLINE: {
    notification_title: 'Sensor Offline',
    notification_message:
      "{deviceName} has stopped reporting. Please check it's powered and connected.",
    user_action: 'View Device',
    deep_link: '/device/{deviceId}',
    notification_category: 'System Health',
    dismissible: false,
    repeat_notification: 'Every 30 min until back online',
    expiry: 'Until resolved',
  },

  // ── Room Occupancy (3-device group) ──────────────────────────────────────
  OCCUPANCY_LONG_STAY: {
    notification_title: 'Long stay alert',
    notification_message: '{resident} has been in the {location} for over {threshold} minutes.',
    user_action: 'Call Resident · View Timeline',
    deep_link: '/timeline/{residentId}',
    notification_category: 'Safety',
    dismissible: true,
    repeat_notification: 'No — single alert per occupancy session',
    expiry: 'Until room becomes vacant',
  },
  OCCUPANCY_NO_MOTION: {
    notification_title: 'No motion detected',
    notification_message:
      'No movement has been detected from {resident} in the {location} for over {threshold} minutes.',
    user_action: 'Call Resident · View Timeline',
    deep_link: '/timeline/{residentId}',
    notification_category: 'Safety',
    dismissible: false,
    repeat_notification: 'No — single alert per no-motion episode; resets on motion',
    expiry: 'Until acknowledged or motion resumes',
  },
  OCCUPANCY_UNCONFIRMED: {
    notification_title: 'Please check in',
    notification_message:
      "We haven't been able to confirm {resident}'s status in the {location} for a while. Please check on them when you can.",
    user_action: 'Call Resident · View Timeline',
    deep_link: '/timeline/{residentId}',
    notification_category: 'Safety',
    dismissible: true,
    repeat_notification: 'No — single alert per stuck-occupied episode',
    expiry: 'Until resolved or room resets',
  },

  // ── Room Occupancy V4 (2-sensor: doorway PIR + inside PIR) ──────────────
  V4_INACTIVITY_ALERT: {
    notification_title: 'No movement detected',
    notification_message:
      'No movement detected in the bathroom for {threshold} minutes. Someone may need help. Please check.',
    user_action: 'Call Resident · View Timeline',
    deep_link: '/timeline/{residentId}',
    notification_category: 'Safety',
    dismissible: false,
    repeat_notification: 'Every 5 min until acknowledged or movement resumes',
    expiry: 'Until acknowledged or movement resumes',
  },
  V4_ALERT_REPEAT: {
    notification_title: 'No movement detected',
    notification_message:
      'No movement detected in the bathroom for {threshold} minutes. Someone may need help. Please check.',
    user_action: 'Call Resident · View Timeline',
    deep_link: '/timeline/{residentId}',
    notification_category: 'Safety',
    dismissible: false,
    repeat_notification: 'Every 5 min until acknowledged or movement resumes',
    expiry: 'Until acknowledged or movement resumes',
  },
  V4_ALL_CLEAR: {
    notification_title: 'Movement detected again',
    notification_message: 'Movement detected again in the bathroom.',
    user_action: 'View Timeline',
    deep_link: '/timeline/{residentId}',
    notification_category: 'Safety',
    dismissible: true,
    repeat_notification: 'No',
    expiry: '24 hours',
  },
  V4_LONG_STAY: {
    notification_title: 'Extended stay',
    notification_message: 'Someone has been in the bathroom for {threshold} minutes.',
    user_action: 'Call Resident · View Timeline',
    deep_link: '/timeline/{residentId}',
    notification_category: 'Safety',
    dismissible: true,
    repeat_notification: 'No — one push per level per occupancy session',
    expiry: 'Until room becomes vacant',
  },
  V4_SAFETY_CEILING: {
    notification_title: 'Please check',
    notification_message: 'Someone has been in the bathroom for {threshold} hours. Please check.',
    user_action: 'Call Resident · View Timeline',
    deep_link: '/timeline/{residentId}',
    notification_category: 'Safety',
    dismissible: false,
    repeat_notification: 'No — single alert per occupancy session',
    expiry: 'Until acknowledged or room resets',
  },
};

notification_events_list.forEach((e) => {
  Object.assign(e, backend_event_copy[e.backend_event] || {});
});

export {
  TIER,
  PRIORITY,
  DELIVERY,
  RECIPIENT,
  DeviceCategory,
  notification_events_list,
  get_event,
  implemented_events_list,
  get_modules,
  get_device_categories,
};
export default notification_events_list;
